- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      src:  /var/lib/awx/projects/_14__project_mi/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes

