- hosts: "all"
  become: true

- name: Copy a test file
  hosts: "all"
  tasks:
  - name: copy a test file
    copy:
      src:  ~/resolv.conf
      dest: /etc/
      owner: root
      group: root
      mode: '0644'
